---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Install basics
      import_tasks: tasks/basics.yaml
      tags: [ basic_virtualization_install ]
    
    - name: Install Packer and Vagrant role
      import_tasks: tasks/vagpak.yaml
      tags: [ basic_virtualization_install ]
    
    - name: Install virtualbox
      import_tasks: tasks/vbox.yaml
      tags: [ basic_virtualization_install ]

