---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Install basics
      import_tasks: tasks/basic.yaml
      tags: [ basic_virtualization_install ]
    
    - name: Install Packer
      import_tasks: tasks/packer.yaml
      tags: [ basic_virtualization_install ]
    
    - name: Install vagrant
      import_tasks: tasks/vagrant.yaml
      tags: [ basic_virtualization_install ]
    
    - name: Install virtualbox
      import_tasks: tasks/vbox.yaml
      tags: [ basic_virtualization_install ]

