---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Install basics
      import_tasks: tasks/basics.yaml
      tags: [ basic ]
    
    - name: Install Packer and Vagrant role
      import_tasks: tasks/vagpak.yaml
      tags: [ vagrant, packer ]
    
    # - name: Install virtualbox
    #   import_tasks: tasks/vbox.yaml
    #   tags: [ basic_virtualization_install ]

    - name: libvirt Install
      import_tasks: tasks/libvirt.yaml
      tags: [ libvirt ]