---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Do Check and Install basic_installs if not already completed.
      import_tasks: tasks/basics_checks.yaml
      tags: [ basic ]
    
    - name: Install Packer and Vagrant role
      import_tasks: tasks/vagpak.yaml
      tags: [ vagrant, packer ]

    - name: libvirt Install
      import_tasks: tasks/libvirt.yaml
      tags: [ libvirt ]

    - name: Clone Base Images
      import_tasks: tasks/clone_base_vms.yaml
      tags: [ base_images ]
      when: base_image_pull is true

    
