---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Do Check and Install basic_installs if not already completed.
      import_tasks: tasks/basics_checks.yaml
      tags: [ basic ]
    
    - name: Install Packer and Vagrant role
      import_tasks: tasks/vagpak.yaml
      tags: [ vagrant_packer_install ]

    - name: libvirt Install
      import_tasks: tasks/libvirt.yaml
      tags: [ libvirt ]

    # Removed and put in at later in workflow
    # - name: Clone Base Images
    #   import_tasks: tasks/clone_base_vms.yaml
    #   tags: [ base_images ]
    #   when: BASE_IMAGE_PULL is true

    
