---

- name: Update yum cache
  yum:
    update_cache: yes

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - perl
      - elfutils-libelf-devel
      - wget
      - gnupg2
      - yum-utils
      - dnf-plugins-core

- name: Enable epel repo
  dnf:
    name: epel-release

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest