- name: Update yum cache
  yum:
    update_cache: yes
  
- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - perl
      - elfutils-libelf-devel
      - wget
      - gnupg2
      - yum-utils
      - dnf-plugins-core
      - git
      - qemu-kvm
      - libvirt
      - virt-manager
      - virt-install
      - bridge-utils
      - virt-top
      - libguestfs-tools
      - virt-viewer

- name: Enable epel repo
  dnf:
    name: epel-release

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Enable RDP
  import_tasks: enable_rdp.yaml
  when: enableRDP is true
  tags: [ RDPEnabled ]

- name: Add File for Check
  file: 
    path: /root/.basic_installed_true
    state: touch
  
