---

- name: Update yum cache
  yum:
    update_cache: yes

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - perl
      - elfutils-libelf-devel
      - wget
      - gnupg2
      - yum-utils
      - dnf-plugins-core
      - akmods
      

- name: Enable epel repo
  dnf:
    name: epel-release

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/crt/ansible.com.crt
    privatekey_path: /etc/ssl/private/ansible.com.pem
    csr_path: /etc/ssl/csr/ansible.com.csr
    provider: selfsigned