---

- name: Clone Base VMs
  git:
    repo: git@github.com:bvaughn123/mk_vm_test_thingys.git
    dest: "/home/{{ GIT_USER }}/base_images"
  become: yes
  become_user: "{{ GIT_USER }}"
  when: base_image_pull == True

