---

- name: Clone Base VMs
  git:
    repo: git@github.com:bvaughn123/mk_vm_test_thingys.git
    dest: "/home/{{ REMOTE_USER }}/base_images"
  become: yes
  become_user: "{{ REMOTE_USER }}"
  when: BASE_IMAGE_PULL == True

