---

- name: Install Vagrant and Packer
  import_role:
    name: hashicorp
  vars:
    install_vagrant_packer: True
  register: vp_install

- name: Install Libvirt vagrant plugin
  shell: vagrant install plugin vagrant-libvirt
  when: vp_install.rc == 0
