- name: Add VirtualBox repository
  yum_repository:
    name: virtualbox
    description: Oracle VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/el/8/$basearch
    gpgcheck: no
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    enabled: yes

- name: Update yum cache
  yum:
    update_cache: yes

- name: Install VirtualBox
  package:
    name: VirtualBox-7.0
    state: present

- name: Start and enable the VirtualBox service
  service:
    name: vboxdrv
    state: started
    enabled: yes

- name: Add user to vboxusers group 
  user:
    name: "{{ ansible_user }}"
    groups: vboxusers
    append: yes