- name: Add VirtualBox 
  get_url:
    url: http://download.virtualbox.org/virtualbox/rpm/rhel/8/x86_64/VirtualBox-5.2-5.2.34_133893_el8-1.x86_64.rpm
    destination: /tmp/VirtualBox.x86_64.rpm

- name: install rpm 
  yum:
    name: /tmp/VirtualBox.x86_64.rpm
    state: present


- name: Update yum cache
  yum:
    update_cache: yes

- name: Install VirtualBox
  package:
    name: VirtualBox-7.0.10
    state: present

- name: Start and enable the VirtualBox service
  service:
    name: vboxdrv
    state: started
    enabled: yes

- name: Add user to vboxusers group 
  user:
    name: "{{ ansible_user }}"
    groups: vboxusers
    append: yes