---

- name: Update yum cache
  yum:
    update_cache: yes

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - perl
      - elfutils-libelf-devel
      - wget

- name: Get VBox asc
  get_url: 
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    dest: /tmp/oracle_vbox.asc

- name: Install Vbox asc
  rpm_key: 
  key: /tmp/oracle_vbox.asc

- name: vbox repo Install
  get_url:
    url: http://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
    dest: etc/yum.repos.d/virtualbox.repo

- name: Update yum cache
  yum:
    update_cache: yes

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - virtualbox
      - virtualbox-ext-pack
      - vagrant
      - ansible
      - packer
      

- name: Start and enable the VirtualBox service
  service:
    name: vboxdrv
    state: started
    enabled: yes

- name: Add user to vboxusers group 
  user:
    name: "{{ ansible_user }}"
    groups: vboxusers
    append: yes
