---

- name: Configure hashicorp 
  when: vagpak is true

  block:
    - name: Configure hashicorp repo
      template:
        src: hashicorp.repo.j2
        dest: /etc/yum.repos.d/hashicorp.repo
        owner: root
        group: root
        mode: "0644"

    - name: Install packer and vagrant
      dnf:
        name: [ "packer", "vagrant" ]
        state: present

